### ISSUE TITLE
doubts about MinMaxScaler() 

### ISSUE THREAD

**Issue by castaway1990** [PennLINC/Vogel_PLS_Tx-Space#1]
Thank you and congrats for the terrific job,

I was trying to understand a little bit more about this preprocessing step in order to apply the same framework to some of my data. You are scaling the whole dataset to min-max values of only a part of it, is that correct? Is that just to overcome expected biological differencies among samples or is that a required step to tune different datasets counts distributions? I'm trying to project an external dataset on pre-defined PLS  from a training set, do you think including this scaling passage (in my case the ext data to reference) could improve the transform?

Thanks a lot!

```
mmmod = MinMaxScaler().fit(exp[list(set(cntrl) & set(younger))].T)
# apply AHBA PCA model to GTEx data
hb_pcatfm = pcamod.transform(mmmod.transform(exp[exp.columns[:-1]].T))
```

**Comment by illdopejake** [comment]
Hi @castaway1990 

Thanks for the kind words, and for raising this issue! Yeah so two things are happening here: 

First, I'm MinMax scaling because the Allen Human Brain Atlas data (which served as the discovery sample) is all 0-1 normalized. This solution is actually imperfect -- ideally we'd use the exact same normalization in this dataset as we do in the Allen, but that isn't possible given differences across the two datasets. So, by at least constraining the value range in the new dataset to be the same as the discovery dataset, we are in theory increasing the likelihood of generalization.

The second thing that's happening here is that we are MinMax scaling on just a subset of the new data. The reason is because the Allen Human Brain Atlas is based on adult humans between the ages of 20 and 60. Because gene expression changes somewhat with aging and rather dramatically during development, we want to make sure we are normalizing the new dataset based on individuals of the same age. You'll see we do this in the other datasets, when we e.g. base the normalization on Humans and leave the non-human primates out of the fitting step. However, once we establish the normalization on this subset that is similar to the discovery dataset, we apply it to the whole dataset.

So to answer the question directly -- I don't think this is a *necessary* step but I think it's highly recommended in this particular context. It might not be necessary in your context. But having the values be along a similar range, and basing that normalization on a subset as similar as possible to the discovery dataset, are recommended steps.

Let me know if that doesn't make sense or if you have some follow-up questions.
