### ISSUE TITLE
Question about variable selection in NB02_PLSModelFitting

### ISSUE THREAD

**Issue by yhxdexy738** [PennLINC/Vogel_PLS_Tx-Space#2]
First and foremost, I want to express my gratitude for sharing your code. It has been incredibly helpful in my project.

While running the code in NB02_PLSModelFitting, I encountered a minor issue. In [In] 13, during the perform train-test split, I noticed that the variables tr_y and te_y are derived from the columns 'mni_nlin_y', 'mni_nlin_z', and 'abs_mni_nlin_x' in the 'data/gxp_correlation_wholebrain_results_NEW.csv' file. I'm curious as to why these columns are used instead of 'mni_x', 'mni_y', and 'mni_z'. Could you kindly explain how these data were calculated and why this operation is necessary? I apologize if this question sounds a bit naive, but I'm genuinely eager to understand the reasoning behind it.

Thank you very much for your time and assistance. I truly appreciate your expertise and willingness to help.

**Comment by illdopejake** [comment]
Hi @yhxdexy738 , thanks for your question.

The original MNI coordinates provided by the Allen Institute did not account for nonlinear deformations. If you are not a neuroimager, that basically means that when each donor brain was transformed into the standard brain coordinates, only linear transformations were used. This resulted in a fairly inaccurate representation of where in the brain the samples were extracted from. So, a few different groups went back and performed the transformations again, this time incorporating nonlinear deformations. Here are some examples:

https://github.com/chrisgorgo/alleninf
https://doi.org/10.5281/zenodo.2483290

This issue is also discussed a bit in [this paper](https://www.sciencedirect.com/science/article/pii/S1053811919300114), as well as [this one](https://elifesciences.org/articles/72129#content:~:text=the%20current%20manuscript.-,Use%20non%2Dlinear%20MNI%20coordinates,-Request%20a%20detailed).

So, the "nlin" stands for nonlinear and represents more accurate coordinates. The reason we took the absolute value of the X coordinates is that PLS is a linear model. We expected medial-lateral variation, and not that much lateralized differences. In other words, positive and negative values for Y and Z represent anterior vs posterior and dorsal vs ventral, respectively. With X, positive and negative values represent left vs right, when what we really want is medial vs lateral. So, taking the absolute value resolves this.

Sorry if this is not coherent. Let me know if anything isn't clear or if I can give a better explanation.

--Jake

**Comment by yhxdexy738** [comment]
Thank you so much for your detailed explanation! I really appreciate your help in clarifying the issue, and I now have a better understanding of the variation and the need for this transformation.Thank you again for your time and assistance!
